future4code/cruz-labe-food5

src/constants/colors.js
src/constants/theme.js
src/constants/urls.js

[feat] constants added

---

src/services/users.js

criação do login e signup

---

package-lock.json
package.json
src/pages/ProfilePage/ProfilePage.js
src/pages/ProfilePage/styled.js

página de perfil feita, faltam pequenos ajustes

---

src/global/GlobalState.js
src/pages/RestaurantPage/RestaurantPage.js

página de restaurante iniciada

---

src/pages/ProfilePage/ProfilePage.js
src/pages/SignUpPage/SignUpPage.js

bugs corrigidos

---

src/components/CartFoodInfoCard.js
src/components/Teaser/Teaser.js
src/components/Teaser/styledTeaser.js
src/pages/CartPage/CartPage.js
src/pages/CartPage/styled.js
src/pages/InitialPage/InitialPage.js

cart em andamento

---

package.json
src/pages/SignUpPage/SignUpPage.js
src/pages/SignUpPage/styled.js

mais alterações no cadastro

---

src/pages/LoginPage/LoginPage.js
src/pages/LoginPage/styled.js

modificação da login page

---

src/hooks/useNoAddress.js
src/pages/LoginPage/LoginPage.js
src/pages/SignUpPage/SignUpPage.js
src/routes/Router.js

[feat] criação da tela de login

---

README.md
package-lock.json
package.json
src/App.js
src/components/CartFoodInfoCard.js
src/components/CartFoodInfoCard/CartFoodInfoCard.js
src/components/CartFoodInfoCard/styledFoodInfo.js
src/components/Loading/Loading.js
src/components/Loading/styledLoading.js
src/pages/CartPage/CartPage.js
src/pages/CartPage/styled.js
src/pages/ProfilePage/ProfilePage.js
src/pages/SignUpPage/SignUpPage.js
src/pages/SignUpPage/styled.js
src/services/utilitiesDate.js

CartPage e InfoCard prontos. Inclusão de componente Loading e utilities para apresentação da data na tela.

---

src/pages/CartPage/styled.js
src/pages/LoginPage/LoginPage.js
src/routes/coordinator.js
src/services/users.js

[fix(users)] correção de bugs referentes aos imports do componente

---

src/components/FoodCard/FoodCard.js
src/components/FoodCard/style.js
src/global/GlobalState.js
src/pages/CartPage/CartPage.js
src/pages/RestaurantPage/RestaurantPage.js
src/pages/RestaurantPage/styled.js

página de detalhes de restaurante em andamento

---

src/services/users.js

[fix(users)] correção de path login/signup

---

src/pages/SignUpPage/SignUpPage.js
src/pages/SignUpPage/styled.js

estilizações e regex

---

src/pages/EditAddressPage/EditAddressPage.js
src/pages/EditProfilePage/EditProfilePage.js
src/pages/EditProfilePage/styled.js
src/pages/ProfilePage/ProfilePage.js
src/pages/ProfilePage/styled.js

Guilherme5

---

src/pages/EditAddressPage/EditAddressPage.js
src/pages/EditProfilePage/EditProfilePage.js
src/pages/ProfilePage/ProfilePage.js
src/pages/ProfilePage/styled.js

ajustes no profilePage, editProfile e editAddress

---

src/components/NavigationBar/BottomNavigation.js
src/hooks/useRequestData.js
src/pages/HomePage/HomePage.js
src/pages/HomePage/styled.js

[feat] inicio implementação HOME

---

src/components/FoodCard/FoodCard.js
src/pages/EditAddressPage/EditAddressPage.js
src/pages/RestaurantPage/RestaurantPage.js

avançando na página de detalhes de restaurante

---

src/hooks/useRequestData.js
src/pages/HomePage/HomePage.js
src/routes/coordinator.js

[fix] erro do useRequestData

---

src/pages/SignUpPage/SignUpPage.js
src/pages/SignUpPage/styled.js

Visibilidade da senha

---

src/pages/EditAddressPage/EditAddressPage.js
src/pages/EditAddressPage/styled.js
src/pages/EditProfilePage/EditProfilePage.js
src/pages/EditProfilePage/styled.js
src/pages/ProfilePage/ProfilePage.js
src/pages/ProfilePage/styled.js
src/pages/SignUpPage/SignUpPage.js

layout profile, editDetails e edidAddress

---

src/pages/ProfilePage/ProfilePage.js
src/pages/ProfilePage/styled.js

estilização

---

src/pages/EditAddressPage/EditAddressPage.js

Tentativa edit

---

src/pages/HomePage/HomePage.js
src/pages/HomePage/styled.js

criação dos cards dos restaurantes e input de pesquisa

---

src/pages/HomePage/HomePage.js

[feat] concluido nas funcionalidades

---

src/pages/ProfilePage/ProfilePage.js
src/pages/ProfilePage/styled.js
src/services/utilitiesDate.js

histórico de pedidos

---

src/pages/ProfilePage/ProfilePage.js
src/pages/ProfilePage/styled.js
src/pages/SignUpPage/SignUpPage.js

card histórico

---

src/components/FoodCard/FoodCard.js
src/pages/HomePage/HomePage.js
src/pages/LoginPage/LoginPage.js
src/pages/LoginPage/styled.js
src/pages/RestaurantPage/RestaurantPage.js

[feat] concluido nas funcionalidades e styled login concluido
